# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\code\embedded\Python\04_Tools\ui\SerialSetingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SerialSettingDialog(object):
    def setupUi(self, SerialSettingDialog):
        SerialSettingDialog.setObjectName("SerialSettingDialog")
        SerialSettingDialog.resize(280, 194)
        self.verticalLayout = QtWidgets.QVBoxLayout(SerialSettingDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(SerialSettingDialog)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.cb_data_bits = QtWidgets.QComboBox(SerialSettingDialog)
        self.cb_data_bits.setObjectName("cb_data_bits")
        self.cb_data_bits.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_data_bits)
        self.Label_2 = QtWidgets.QLabel(SerialSettingDialog)
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.cb_stop_bits = QtWidgets.QComboBox(SerialSettingDialog)
        self.cb_stop_bits.setObjectName("cb_stop_bits")
        self.cb_stop_bits.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_stop_bits)
        self.Label_3 = QtWidgets.QLabel(SerialSettingDialog)
        self.Label_3.setObjectName("Label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.cb_verify_bits = QtWidgets.QComboBox(SerialSettingDialog)
        self.cb_verify_bits.setObjectName("cb_verify_bits")
        self.cb_verify_bits.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cb_verify_bits)
        self.Label_4 = QtWidgets.QLabel(SerialSettingDialog)
        self.Label_4.setObjectName("Label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.cb_flow_control = QtWidgets.QComboBox(SerialSettingDialog)
        self.cb_flow_control.setObjectName("cb_flow_control")
        self.cb_flow_control.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cb_flow_control)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(SerialSettingDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SerialSettingDialog)
        self.buttonBox.accepted.connect(SerialSettingDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SerialSettingDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SerialSettingDialog)

    def retranslateUi(self, SerialSettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SerialSettingDialog.setWindowTitle(_translate("SerialSettingDialog", "Dialog"))
        self.Label.setText(_translate("SerialSettingDialog", "数据位:"))
        self.cb_data_bits.setItemText(0, _translate("SerialSettingDialog", "8"))
        self.Label_2.setText(_translate("SerialSettingDialog", "停止位:"))
        self.cb_stop_bits.setItemText(0, _translate("SerialSettingDialog", "1"))
        self.Label_3.setText(_translate("SerialSettingDialog", "校验位:"))
        self.cb_verify_bits.setItemText(0, _translate("SerialSettingDialog", "None"))
        self.Label_4.setText(_translate("SerialSettingDialog", "流控制:"))
        self.cb_flow_control.setItemText(0, _translate("SerialSettingDialog", "None"))
